services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - etc/.env
    ports:
      - "8000:8000"

  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      - API_URL=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api